---
- name: "Test playbook"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "System info"
      ansible.builtin.setup:
        filter:
          - 'ansible_processor_cores'
          - 'ansible_memtotal_mb'
          - 'ansible_mounts'
      register: system_info
   
    - name: "Display System Info"        
      debug:
        var: ansible_facts
    
    - name: "Calculate Storage Info"
      set_fact:
        aux_storage_size: 0
        total_storage_size: "{{ aux_storage_size + item.size_total }}"
      loop: "{{ system_info.ansible_facts.ansible_mounts }}"

    - name: "Display Total Storage Info"
      debug:
        var: total_storage_size


