---
- name: "Test Playbook"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Getting system info"
      ansible.builtin.setup:
        filter:
          #obtains cpu information
          - 'ansible_processor_cores'
          #obtains memory information
          - 'ansible_memtotal_mb'
          #obtains information of how many filesystem there are
          #obtains storage information
          - 'ansible_mounts'
      register: system_info

    - name: "Display processor cores"
      debug:
        msg: "Processor Cores: {{ system_info.ansible_facts.ansible_processor_cores }}"

    - name: "Display memory information"
      debug:
        msg: "Total Memory: {{ system_info.ansible_facts.ansible_memtotal_mb | human_readable }}"

    - name: "Display number of filesystems"
      debug:
        msg: "Number of Filesystems: {{ system_info.ansible_facts.ansible_mounts | length }}"
    
    - name: "Calculate and display total storage"
      debug:
        msg: "Total Storage: {{ system_info.ansible_facts.ansible_mounts | map(attribute='size_total') | human_readable | sum }}"