---
- name: "Test Playbook"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "System info"
      ansible.builtin.setup:
        filter:
          - 'ansible_processor_cores'
          - 'ansible_memtotal_mb'
      register: system_info

    - name: "Display processor cores"
      debug:
        var: system_info.processor_cores

    - name: "Display memory information"
      debug:
        var: system_info.memtotal_mb