---
- name: "Test playbook"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "System info"
      ansible.builtin.setup:
        filter:
          - 'ansible_processor_cores'
          - 'ansible_memtotal_mb'
          - 'ansible_mounts'
      register: system_info
   
    - name: "Display System Info"        
      debug:
        var: ansible_facts
    
    - name: "Calculate Storage Info"
      set_fact:
        #default sirve para crear una variable si no existe y le agrega el valor entre parentesis
        #El siguiente pipe convierte la salida de str a int
        total_storage_size: "{{ total_storage_size|default(0) | int + item.size_total | int | human_readable }}"
      loop: "{{ system_info.ansible_facts.ansible_mounts }}"

    - name: "Display Total Storage Info"
      debug:
        var: total_storage_size


