--- 
- name: "Linux distribution information"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Get distribution info"
      file:
        path: /etc/os-release
        state: present
      register: distribution_info

    - name: "Check if distribution is Red Hat or similar"
      set_fact:
        is_redhat: "{{ distribution_info.content | match('RedHat|CentOS|Fedora') }}"