--- 
- name: "Linux distribution information"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Determine distro"
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_distribution_version'
          - 'ansible_distribution_release'
      #register: distro_info

    - name: "Check if redhat or similar"
      ansible.builtin.set_fact:
        is_redhat: "{{ ansible_distribution in ['RedHat', 'CentOS', 'Fedora'] }}"

    - name: "Display distro information"
      ansible.builtin.debug:
        msg: 
          "{% if is_redhat %}
            The installed RedHat or similar distro is 
            {{ ansible_distribution }}
            {{ ansible_distribution_release }} 
            {{ ansible_distribution_version }}
          {% else %}
            The installed distro is not RedHat or similar, the distro is: 
            {{ ansible_distribution }} 
            {{ ansible_distribution_release }}
            {{ ansible_distribution_version }}
          {% endif %}"

    - name: If the distro is redhat or similar verify the installation of nmap
      ansible.builtin.package_facts:
        manager: auto
      when: is_redhat

    - name: Show nmap information
      ansible.builtin.debug:
        msg: "nmap is installed on {{ ansible_distribution }} 
          {{ ansible_distribution_release }} 
          {{ ansible_distribution_version }}"
      when: is_redhat

  
