---
- name: system users and groups
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Getting system users info
      ansible.builtin.getent:
        database: passwd
        split: ':'

    - name: Display list of system users
      ansible.builtin.debug:
        msg: "{{ getent_passwd | list }}"

    - name: Getting system groups info
      ansible.builtin.getent:
        database: group
        split: ':'
    #register: lgroups

    - name: Display list of system groups
      ansible.builtin.debug:
        msg: "{{ getent_group | list }}"

    - name: Read content from /etc/sudoers
      ansible.builtin.slurp:
        src: /etc/sudoers
      register: sudoers_file

    - name: Filtrar líneas relevantes
      ansible.builtin.shell:
        cmd: "grep -E '^(\\S+)\\s+ALL=\\(ALL:ALL\\) ALL' /etc/sudoers"
      register: filtered_lines

    - name: Mostrar líneas filtradas
      ansible.builtin.debug:
        msg: "{{ filtered_lines.stdout_lines }}"



      
